/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResidentService } from "../resident.service";
import { ResidentCreateInput } from "./ResidentCreateInput";
import { Resident } from "./Resident";
import { ResidentFindManyArgs } from "./ResidentFindManyArgs";
import { ResidentWhereUniqueInput } from "./ResidentWhereUniqueInput";
import { ResidentUpdateInput } from "./ResidentUpdateInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";

export class ResidentControllerBase {
  constructor(protected readonly service: ResidentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Resident })
  async createResident(
    @common.Body() data: ResidentCreateInput
  ): Promise<Resident> {
    return await this.service.createResident({
      data: {
        ...data,

        unit: data.unit
          ? {
              connect: data.unit,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        email: true,
        phoneNumber: true,

        unit: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Resident] })
  @ApiNestedQuery(ResidentFindManyArgs)
  async residents(@common.Req() request: Request): Promise<Resident[]> {
    const args = plainToClass(ResidentFindManyArgs, request.query);
    return this.service.residents({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        email: true,
        phoneNumber: true,

        unit: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Resident })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async resident(
    @common.Param() params: ResidentWhereUniqueInput
  ): Promise<Resident | null> {
    const result = await this.service.resident({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        email: true,
        phoneNumber: true,

        unit: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Resident })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateResident(
    @common.Param() params: ResidentWhereUniqueInput,
    @common.Body() data: ResidentUpdateInput
  ): Promise<Resident | null> {
    try {
      return await this.service.updateResident({
        where: params,
        data: {
          ...data,

          unit: data.unit
            ? {
                connect: data.unit,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          email: true,
          phoneNumber: true,

          unit: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Resident })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResident(
    @common.Param() params: ResidentWhereUniqueInput
  ): Promise<Resident | null> {
    try {
      return await this.service.deleteResident({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          email: true,
          phoneNumber: true,

          unit: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: ResidentWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,
        paymentDate: true,

        resident: {
          select: {
            id: true,
          },
        },

        stripePaymentId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  async connectPayments(
    @common.Param() params: ResidentWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateResident({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  async updatePayments(
    @common.Param() params: ResidentWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateResident({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  async disconnectPayments(
    @common.Param() params: ResidentWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateResident({
      where: params,
      data,
      select: { id: true },
    });
  }
}
