/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UnitService } from "../unit.service";
import { UnitCreateInput } from "./UnitCreateInput";
import { Unit } from "./Unit";
import { UnitFindManyArgs } from "./UnitFindManyArgs";
import { UnitWhereUniqueInput } from "./UnitWhereUniqueInput";
import { UnitUpdateInput } from "./UnitUpdateInput";
import { ResidentFindManyArgs } from "../../resident/base/ResidentFindManyArgs";
import { Resident } from "../../resident/base/Resident";
import { ResidentWhereUniqueInput } from "../../resident/base/ResidentWhereUniqueInput";

export class UnitControllerBase {
  constructor(protected readonly service: UnitService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Unit })
  async createUnit(@common.Body() data: UnitCreateInput): Promise<Unit> {
    return await this.service.createUnit({
      data: {
        ...data,

        building: data.building
          ? {
              connect: data.building,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        unitNumber: true,

        building: {
          select: {
            id: true,
          },
        },

        dueAmount: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Unit] })
  @ApiNestedQuery(UnitFindManyArgs)
  async units(@common.Req() request: Request): Promise<Unit[]> {
    const args = plainToClass(UnitFindManyArgs, request.query);
    return this.service.units({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        unitNumber: true,

        building: {
          select: {
            id: true,
          },
        },

        dueAmount: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Unit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async unit(
    @common.Param() params: UnitWhereUniqueInput
  ): Promise<Unit | null> {
    const result = await this.service.unit({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        unitNumber: true,

        building: {
          select: {
            id: true,
          },
        },

        dueAmount: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Unit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUnit(
    @common.Param() params: UnitWhereUniqueInput,
    @common.Body() data: UnitUpdateInput
  ): Promise<Unit | null> {
    try {
      return await this.service.updateUnit({
        where: params,
        data: {
          ...data,

          building: data.building
            ? {
                connect: data.building,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          unitNumber: true,

          building: {
            select: {
              id: true,
            },
          },

          dueAmount: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Unit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUnit(
    @common.Param() params: UnitWhereUniqueInput
  ): Promise<Unit | null> {
    try {
      return await this.service.deleteUnit({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          unitNumber: true,

          building: {
            select: {
              id: true,
            },
          },

          dueAmount: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/residents")
  @ApiNestedQuery(ResidentFindManyArgs)
  async findResidents(
    @common.Req() request: Request,
    @common.Param() params: UnitWhereUniqueInput
  ): Promise<Resident[]> {
    const query = plainToClass(ResidentFindManyArgs, request.query);
    const results = await this.service.findResidents(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        email: true,
        phoneNumber: true,

        unit: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/residents")
  async connectResidents(
    @common.Param() params: UnitWhereUniqueInput,
    @common.Body() body: ResidentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      residents: {
        connect: body,
      },
    };
    await this.service.updateUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/residents")
  async updateResidents(
    @common.Param() params: UnitWhereUniqueInput,
    @common.Body() body: ResidentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      residents: {
        set: body,
      },
    };
    await this.service.updateUnit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/residents")
  async disconnectResidents(
    @common.Param() params: UnitWhereUniqueInput,
    @common.Body() body: ResidentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      residents: {
        disconnect: body,
      },
    };
    await this.service.updateUnit({
      where: params,
      data,
      select: { id: true },
    });
  }
}
