/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BuildingService } from "../building.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BuildingCreateInput } from "./BuildingCreateInput";
import { Building } from "./Building";
import { BuildingFindManyArgs } from "./BuildingFindManyArgs";
import { BuildingWhereUniqueInput } from "./BuildingWhereUniqueInput";
import { BuildingUpdateInput } from "./BuildingUpdateInput";
import { UnitFindManyArgs } from "../../unit/base/UnitFindManyArgs";
import { Unit } from "../../unit/base/Unit";
import { UnitWhereUniqueInput } from "../../unit/base/UnitWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BuildingControllerBase {
  constructor(
    protected readonly service: BuildingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Building })
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBuilding(
    @common.Body() data: BuildingCreateInput
  ): Promise<Building> {
    return await this.service.createBuilding({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        streetAddress1: true,
        streetAddress2: true,
        postalCode: true,
        countryCode: true,
        phone: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Building] })
  @ApiNestedQuery(BuildingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async buildings(@common.Req() request: Request): Promise<Building[]> {
    const args = plainToClass(BuildingFindManyArgs, request.query);
    return this.service.buildings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        streetAddress1: true,
        streetAddress2: true,
        postalCode: true,
        countryCode: true,
        phone: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Building })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async building(
    @common.Param() params: BuildingWhereUniqueInput
  ): Promise<Building | null> {
    const result = await this.service.building({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        streetAddress1: true,
        streetAddress2: true,
        postalCode: true,
        countryCode: true,
        phone: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Building })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBuilding(
    @common.Param() params: BuildingWhereUniqueInput,
    @common.Body() data: BuildingUpdateInput
  ): Promise<Building | null> {
    try {
      return await this.service.updateBuilding({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          streetAddress1: true,
          streetAddress2: true,
          postalCode: true,
          countryCode: true,
          phone: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Building })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBuilding(
    @common.Param() params: BuildingWhereUniqueInput
  ): Promise<Building | null> {
    try {
      return await this.service.deleteBuilding({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          streetAddress1: true,
          streetAddress2: true,
          postalCode: true,
          countryCode: true,
          phone: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/units")
  @ApiNestedQuery(UnitFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Unit",
    action: "read",
    possession: "any",
  })
  async findUnits(
    @common.Req() request: Request,
    @common.Param() params: BuildingWhereUniqueInput
  ): Promise<Unit[]> {
    const query = plainToClass(UnitFindManyArgs, request.query);
    const results = await this.service.findUnits(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        unitNumber: true,

        building: {
          select: {
            id: true,
          },
        },

        dueAmount: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/units")
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "update",
    possession: "any",
  })
  async connectUnits(
    @common.Param() params: BuildingWhereUniqueInput,
    @common.Body() body: UnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      units: {
        connect: body,
      },
    };
    await this.service.updateBuilding({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/units")
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "update",
    possession: "any",
  })
  async updateUnits(
    @common.Param() params: BuildingWhereUniqueInput,
    @common.Body() body: UnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      units: {
        set: body,
      },
    };
    await this.service.updateBuilding({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/units")
  @nestAccessControl.UseRoles({
    resource: "Building",
    action: "update",
    possession: "any",
  })
  async disconnectUnits(
    @common.Param() params: BuildingWhereUniqueInput,
    @common.Body() body: UnitWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      units: {
        disconnect: body,
      },
    };
    await this.service.updateBuilding({
      where: params,
      data,
      select: { id: true },
    });
  }
}
